# Generated by Django 5.0.9 on 2026-09-21 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="نام و مشخصات"),
                ),
                (
                    "specialty",
                    models.CharField(blank=True, max_length=200, verbose_name="تخصص"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collaboration_type",
                    models.CharField(
                        choices=[
                            ("consulting", "مشاوره"),
                            ("contracting", "پیمانکاری"),
                            ("research", "پژوهشی"),
                        ],
                        max_length=20,
                        verbose_name="نوع همکاری",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="شماره قرارداد"
                    ),
                ),
                (
                    "contract_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=16,
                        null=True,
                        verbose_name="مبلغ قرارداد",
                    ),
                ),
                (
                    "contract_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ شروع قرارداد"
                    ),
                ),
                (
                    "contract_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ پایان قرارداد"
                    ),
                ),
                (
                    "deliverables_status",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="وضعیت تحویل تعهدات"
                    ),
                ),
            ],
            options={
                "verbose_name": "همکار خارجی",
                "verbose_name_plural": "همکاران خارجی",
            },
        ),
        migrations.CreateModel(
            name="InternalCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="نام و مشخصات"),
                ),
                (
                    "specialty",
                    models.CharField(blank=True, max_length=200, verbose_name="تخصص"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("official", "رسمی"),
                            ("contractual", "پیمانی"),
                            ("project_based", "قراردادی"),
                        ],
                        max_length=20,
                        verbose_name="نوع استخدام",
                    ),
                ),
                (
                    "organizational_unit",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="واحد سازمانی"
                    ),
                ),
                (
                    "role_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نقش/سمت"
                    ),
                ),
            ],
            options={
                "verbose_name": "همکار داخلی",
                "verbose_name_plural": "همکاران داخلی",
            },
        ),
        migrations.CreateModel(
            name="ResearchInstitute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="نام پژوهشکده"
                    ),
                ),
            ],
            options={
                "verbose_name": "پژوهشکده",
                "verbose_name_plural": "پژوهشکده\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="کد پروژه"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان پروژه")),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("research", "پژوهشی"),
                            ("executive", "اجرایی"),
                            ("service", "خدماتی"),
                            ("other", "سایر"),
                        ],
                        default="research",
                        max_length=20,
                        verbose_name="نوع پروژه",
                    ),
                ),
                (
                    "client_or_funder",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="کارفرما / منبع تأمین"
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(
                        verbose_name="تاریخ شروع برنامه\u200cریزی\u200cشده"
                    ),
                ),
                (
                    "planned_end_date",
                    models.DateField(
                        verbose_name="تاریخ پایان برنامه\u200cریزی\u200cشده"
                    ),
                ),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ شروع واقعی"
                    ),
                ),
                (
                    "actual_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ پایان واقعی"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("defined", "تعریف\u200cشده"),
                            ("in_progress", "در حال اجرا"),
                            ("stopped", "متوقف"),
                            ("finished", "خاتمه\u200cیافته"),
                        ],
                        default="defined",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="درصد پیشرفت واقعی"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=18, verbose_name="بودجه"
                    ),
                ),
                (
                    "cost_spent",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="هزینه\u200cی مصرف\u200cشده",
                    ),
                ),
                (
                    "executor_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "executor_assigned_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ انتصاب مجری"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "executor_content_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "model__in": (
                                "internalcollaborator",
                                "externalcollaborator",
                            )
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="نوع موجودیت مجری",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروژه",
                "verbose_name_plural": "پروژه\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_object_id", models.PositiveIntegerField()),
                (
                    "allocation_percent",
                    models.PositiveSmallIntegerField(verbose_name="سهم زمانی (درصد)"),
                ),
                (
                    "role_description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نقش در پروژه"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ شروع تخصیص"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ پایان تخصیص"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person_content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": (
                                "soldier",
                                "internalcollaborator",
                                "externalcollaborator",
                            )
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="نوع نیرو",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="projects.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصیص نیرو",
                "verbose_name_plural": "تخصیص\u200cهای نیرو",
            },
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="کد پروپوزال"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                (
                    "executor_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("research", "پژوهشی"),
                            ("executive", "اجرایی"),
                            ("service", "خدماتی"),
                            ("other", "سایر"),
                        ],
                        default="research",
                        max_length=20,
                        verbose_name="نوع پروژه",
                    ),
                ),
                (
                    "client_or_funder",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="کارفرما / منبع تأمین"
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(verbose_name="تاریخ شروع پیشنهادی"),
                ),
                (
                    "planned_end_date",
                    models.DateField(verbose_name="تاریخ پایان پیشنهادی"),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=18,
                        verbose_name="بودجه پیشنهادی",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="شرح پروپوزال"),
                ),
                (
                    "resource_requirement",
                    models.TextField(blank=True, verbose_name="اعلام نیاز نیرویی"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "ارسال\u200cشده"),
                            ("institute_review", "در حال بررسی در پژوهشکده"),
                            ("academy_review", "در حال بررسی در پژوهشگاه"),
                            ("needs_revision", "نیازمند اصلاح"),
                            ("rejected", "ردشده"),
                            ("approved", "تأییدشده (در انتظار صدور حکم)"),
                            ("in_progress", "در حال اجرا"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "pending_revision_target",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("institute", "شورای علمی پژوهشکده"),
                            ("academy", "شورای پژوهشی پژوهشگاه"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="شورای مرجع اصلاحیه",
                    ),
                ),
                ("current_version", models.PositiveSmallIntegerField(default=1)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تصویب نهایی"
                    ),
                ),
                (
                    "order_issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان صدور حکم مجری"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "executor_content_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "model__in": (
                                "internalcollaborator",
                                "externalcollaborator",
                            )
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="نوع موجودیت مجری پیشنهادی",
                    ),
                ),
                (
                    "research_institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="projects.researchinstitute",
                        verbose_name="پژوهشکده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروپوزال",
                "verbose_name_plural": "پروپوزال\u200cها",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="proposal",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project",
                to="projects.proposal",
                verbose_name="پروپوزال مبنا",
            ),
        ),
        migrations.CreateModel(
            name="ProposalDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveSmallIntegerField()),
                (
                    "council",
                    models.CharField(
                        choices=[
                            ("institute", "شورای علمی پژوهشکده"),
                            ("academy", "شورای پژوهشی پژوهشگاه"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "تأیید"),
                            ("needs_revision", "نیازمند اصلاح"),
                            ("rejected", "رد"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, verbose_name="نظرات / دلایل رد"),
                ),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="projects.proposal",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تصمیم شورا",
                "verbose_name_plural": "تصمیم\u200cهای شورا",
                "ordering": ["-decided_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposalVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "budget",
                    models.DecimalField(decimal_places=0, default=0, max_digits=18),
                ),
                ("planned_start_date", models.DateField()),
                ("planned_end_date", models.DateField()),
                ("resource_requirement", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="projects.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "نسخه\u200cی پروپوزال",
                "verbose_name_plural": "نسخه\u200cهای پروپوزال",
                "ordering": ["proposal", "version_number"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="research_institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="projects.researchinstitute",
                verbose_name="پژوهشکده",
            ),
        ),
        migrations.CreateModel(
            name="Soldier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="نام و مشخصات"),
                ),
                (
                    "specialty",
                    models.CharField(blank=True, max_length=200, verbose_name="تخصص"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "degree",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="مدرک تحصیلی"
                    ),
                ),
                (
                    "service_plan",
                    models.CharField(
                        choices=[
                            ("amrieh", "امریه"),
                            ("alternative", "طرح جایگزین خدمت"),
                            ("other", "سایر"),
                        ],
                        default="amrieh",
                        max_length=20,
                        verbose_name="نوع طرح خدمت",
                    ),
                ),
                (
                    "service_start_date",
                    models.DateField(verbose_name="تاریخ شروع خدمت"),
                ),
                ("service_end_date", models.DateField(verbose_name="تاریخ پایان خدمت")),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_soldiers",
                        to="projects.internalcollaborator",
                        verbose_name="سرپرست مستقیم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سرباز",
                "verbose_name_plural": "سربازان",
            },
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("project", "person_content_type", "person_object_id"),
                name="unique_assignment_per_project_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposalversion",
            constraint=models.UniqueConstraint(
                fields=("proposal", "version_number"), name="unique_proposal_version"
            ),
        ),
    ]
