"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 20:51:13.364054
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.models

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=False),
    sa.Column('account_mask', sa.String(length=4), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('balance_toman', sa.BigInteger(), nullable=False),
    sa.Column('balance_updated_at', app.models.UTCDateTime(), nullable=True),
    sa.Column('balance_source', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', app.models.DecimalText(length=40), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('karat', sa.Integer(), nullable=True),
    sa.Column('price_key', sa.String(length=100), nullable=True),
    sa.Column('manual_value_toman', sa.BigInteger(), nullable=True),
    sa.Column('manual_value_updated_at', app.models.UTCDateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount_toman', sa.BigInteger(), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('lender', sa.String(length=200), nullable=False),
    sa.Column('principal_toman', sa.BigInteger(), nullable=False),
    sa.Column('installment_toman', sa.BigInteger(), nullable=False),
    sa.Column('installments_total', sa.Integer(), nullable=False),
    sa.Column('installments_paid', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('nominal_rate', app.models.DecimalText(length=40), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inputs_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('networth_snapshots',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('assets_toman', sa.BigInteger(), nullable=False),
    sa.Column('liabilities_toman', sa.BigInteger(), nullable=False),
    sa.Column('networth_toman', sa.BigInteger(), nullable=False),
    sa.Column('usd_rate', sa.BigInteger(), nullable=True),
    sa.Column('gold18_rate', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('price_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('price_toman', sa.BigInteger(), nullable=False),
    sa.Column('fetched_at', app.models.UTCDateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_quotes_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_quotes_key'), ['key'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sms_inbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_masked', sa.Text(), nullable=False),
    sa.Column('received_at', app.models.UTCDateTime(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('parse_status', sa.String(length=10), nullable=False),
    sa.Column('parser', sa.String(length=50), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_inbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_inbox_content_hash'), ['content_hash'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('amount_toman', sa.BigInteger(), nullable=False),
    sa.Column('balance_after_toman', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', app.models.UTCDateTime(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sms_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sms_id'], ['sms_inbox.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    with op.batch_alter_table('sms_inbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_inbox_content_hash'))

    op.drop_table('sms_inbox')
    op.drop_table('settings')
    with op.batch_alter_table('price_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_quotes_key'))
        batch_op.drop_index(batch_op.f('ix_price_quotes_fetched_at'))

    op.drop_table('price_quotes')
    op.drop_table('networth_snapshots')
    op.drop_table('loan_analyses')
    op.drop_table('liabilities')
    op.drop_table('income_streams')
    op.drop_table('assets')
    op.drop_table('accounts')
    # ### end Alembic commands ###
