"""price quote units

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 13:43:40.134560
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units', sa.BigInteger(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_quotes', schema=None) as batch_op:
        batch_op.drop_column('units')

    # ### end Alembic commands ###
